const $=id=>document.getElementById(id);let state={gender:'male'};
function show(id){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0)}
$('startBtn').onclick=()=>show('pageForm');$('homeBtn').onclick=()=>show('pageHome');
document.querySelectorAll('.gender button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.gender button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.gender=b.dataset.gender});
document.querySelector('[data-gender="male"]').classList.add('selected');
function num(v){return parseInt(v,10)||0}function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function calc(){let y=num($('year').value),m=num($('month').value),d=num($('day').value),name=$('name').value.trim();if(!name||y<1900||m<1||m>12||d<1||d>31){alert('Нэр, төрсөн огноогоо зөв оруулна уу');return}state.name=name;state.birth=`${y}.${String(m).padStart(2,'0')}.${String(d).padStart(2,'0')}`;let seed=(y+m*7+d*13+name.length*11+(state.gender==='male'?17:29));let debt=clamp(45+(seed%49),30,94);let money=clamp(100-debt+(m*3%22),28,88);let save=clamp(35+((y+d+m)%44),25,86);let main=clamp(Math.round((money+save+(100-debt))/3),22,94);state.result={debt,money,save,main,risk:debt>75?'Өндөр':debt>55?'Дунд':'Бага'};showLoading();}
$('calcBtn').onclick=calc;
function showLoading(){show('pageLoading');let p=0;let texts=['Төрсөн өгөгдлийг тооцоолж байна...','Мөнгөний урсгалыг шалгаж байна...','Өр зээлийн блокийг хэмжиж байна...','Хишгийн савны төлөв гарч байна...'];let t=setInterval(()=>{p+=7;$('barFill').style.width=p+'%';$('loadText').textContent=texts[Math.min(texts.length-1,Math.floor(p/28))];if(p>=100){clearInterval(t);renderResult();show('pageResult')}},120)}
function renderResult(){let r=state.result;$('hello').textContent=`${state.name}, таны санхүүгийн товч оношилгоо гарлаа`;$('mainScore').textContent=r.main+'%';$('debtScore').textContent=r.debt+'%';$('moneyScore').textContent=r.money+'%';$('saveScore').textContent=r.save+'%';$('riskText').textContent=r.risk;$('freeText').innerHTML=`<b>${state.name}</b>, таны мөнгө олох суваг бүрэн хаагдаагүй боловч мөнгө тогтох саванд гацалт ажиглагдаж байна. Өр зээлийн блок <b>${r.debt}%</b> түвшинд гарсан тул ойрын үед яаралтай зээл, батлан даалт, бусдад мөнгө зээлүүлэх шийдвэрт болгоомжтой хандаарай.<br><br>Дэлгэрэнгүй тайланд өр зээл давтагдах шалтгаан, мөнгө хаана гадагшилж байгаа, мөнгөний урсгал нээх тохиромжтой үеийг гаргана.`}
$('packagesBtn').onclick=()=>show('pagePackages');
document.querySelectorAll('.buy').forEach(b=>b.onclick=()=>{state.pack=b.dataset.pack;state.price=b.dataset.price;$('payTitle').textContent=state.pack;$('payPrice').textContent=Number(state.price).toLocaleString('mn-MN')+'₮';$('payCode').textContent=(state.name||'Нэр')+'-'+Math.floor(1000+Math.random()*8999);show('pagePay')});
$('saveOrder').onclick=()=>{let phone=$('phone').value.trim();if(phone.length<6){alert('Утасны дугаараа оруулна уу');return}let orders=JSON.parse(localStorage.getItem('tm_orders')||'[]');orders.unshift({date:new Date().toLocaleString('mn-MN'),name:state.name,birth:state.birth,phone,pack:state.pack,price:state.price,result:state.result});localStorage.setItem('tm_orders',JSON.stringify(orders));alert('Захиалга хадгалагдлаа. Админ хэсгээс харж болно.');renderOrders();show('pageAdmin')};
$('adminBtn').onclick=()=>{renderOrders();show('pageAdmin')};$('clearOrders').onclick=()=>{if(confirm('Бүх захиалгыг цэвэрлэх үү?')){localStorage.removeItem('tm_orders');renderOrders()}};
function renderOrders(){let orders=JSON.parse(localStorage.getItem('tm_orders')||'[]');$('orders').innerHTML=orders.length?orders.map(o=>`<div class="order"><b>${o.name}</b> — ${o.pack}<br>${Number(o.price).toLocaleString('mn-MN')}₮ · ${o.phone}<br><small>${o.birth} · ${o.date}</small></div>`).join(''):'<div class="card">Одоогоор захиалга алга.</div>'}
if('serviceWorker' in navigator){/* дараа sw нэмнэ */}
