import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getFirestore, collection, addDoc, getDocs, query, orderBy, serverTimestamp, doc, updateDoc } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
const firebaseConfig={apiKey:'AIzaSyCptq_EpedA2ok205SoFMBjci5IcID7nWc',authDomain:'mongo-block.firebaseapp.com',projectId:'mongo-block',storageBucket:'mongo-block.firebasestorage.app',messagingSenderId:'161463190344',appId:'1:161463190344:web:cc5e2672ded4900937e97d',measurementId:'G-6074VCDK9W'};
const firebaseApp=initializeApp(firebaseConfig); const db=getFirestore(firebaseApp);
const $=id=>document.getElementById(id); let client={}, selected={};
function showScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0);if(id==='admin')loadOrders()} window.showScreen=showScreen;
function toast(t){const el=$('toast');el.textContent=t;el.style.display='block';setTimeout(()=>el.style.display='none',1600)}
function parseDate(s){let p=s.trim().replaceAll('/','.').replaceAll('-','.').split('.').map(x=>parseInt(x,10));return{year:p[0],month:p[1],day:p[2]}}
function confirmInfo(){const bd=parseDate($('birthDate').value);client={fullName:$('fullName').value.trim(),birth:$('birthDate').value.trim(),phone:$('phone').value.trim(),year:bd.year,month:bd.month,day:bd.day};if(!client.fullName||!client.phone||!client.year||!client.month||!client.day){toast('Мэдээллээ бүрэн оруулна уу');return}$('cName').textContent=client.fullName;$('cBirth').textContent=client.birth;$('cPhone').textContent=client.phone;$('confirmModal').classList.add('show')} window.confirmInfo=confirmInfo;
function closeModal(){$('confirmModal').classList.remove('show')} window.closeModal=closeModal;
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return Math.abs(h)}
function beginScan(){closeModal();showScreen('loading');let p=0,texts=['Төрсөн мэдээллийг уншиж байна...','Мөнгөний энерги тооцоолж байна...','Өрийн блок шалгаж байна...','Хишгийн сав нээж байна...','Санхүүгийн түлхүүр бэлтгэж байна...'];let t=setInterval(()=>{p+=7;if(p>100)p=100;$('bar').style.width=p+'%';$('loadingText').textContent=texts[Math.min(4,Math.floor(p/23))];if(p>=100){clearInterval(t);setTimeout(showResult,500)}},120)} window.beginScan=beginScan;
const zodiacData=[['Матар','♑',120,['Тэвчээр','Хяналт','Хадгалалт']],['Хумх','♒',218,['Шинэ санаа','Сүлжээ','Онлайн орлого']],['Загас','♓',320,['Зөн совин','Уян хатан','Бүтээлч урсгал']],['Хонь','♈',420,['Шуурхай эхлэл','Зориг','Эрсдэл']],['Үхэр','♉',521,['Тогтвортой орлого','Үл хөдлөх','Хуримтлал']],['Ихэр','♊',621,['Харилцаа','Мэдээлэл','Худалдаа']],['Мэлхий','♋',722,['Гэрийн хишиг','Хамгаалалт','Нөөц']],['Арслан','♌',823,['Нэр хүнд','Манлайлал','Том боломж']],['Охин','♍',923,['Нягт тооцоо','Сахилга','Үйлчилгээ']],['Жинлүүр','♎',1023,['Түншлэл','Гэрээ','Тэнцвэр']],['Хилэнц','♏',1122,['Гүн хүч','Өр тайлах','Нууц боломж']],['Нум','♐',1222,['Аялал','Өсөлт','Суралцах орлого']],['Матар','♑',1231,['Тэвчээр','Хяналт','Хадгалалт']]];
function zodiac(m,d){let x=m*100+d;return zodiacData.find(a=>x<=a[2])||zodiacData[0]}
function showResult(){let seed=hash(client.fullName+client.birth+client.phone),total=88+(seed%10),debt=80+(seed%14),flow=82+(seed%12),luck=86+(seed%12),energy=87+(seed%10),zz=zodiac(client.month,client.day);client.result={total,debt,flow,luck,energy,zodiac:zz[0]};$('totalScore').textContent=total;$('debtScore').textContent=debt+'%';$('flowScore').textContent=flow+'%';$('luckScore').textContent=luck+'%';$('energyScore').textContent=energy+'%';$('zodiacName').textContent=zz[0]+'ын орд';$('zodiacSymbol').textContent=zz[1];$('loadingZodiac').textContent=zz[1];$('zodiacText').textContent=zz[0]+' орд нь таны мөнгөтэй харьцах далд хэв маяг, баялаг татах чиглэл, өр зээлийн эрсдэлийг урьдчилан мэдрэх зөнг илэрхийлнэ.';$('zodiacChips').innerHTML=zz[3].map(x=>`<span>${x}</span>`).join('');$('resultTitle').textContent='Таны мөнгөний энерги '+(total>=92?'маш өндөр':'өндөр')+' байна.';showScreen('result')}
function selectPackage(name,price){selected={name,price};$('txn').textContent=client.phone||'утас';$('paidCheck').checked=false;toggleSubmit();showScreen('payment')} window.selectPackage=selectPackage;
function copyText(id){navigator.clipboard?.writeText($(id).textContent.trim());toast('Хууллаа')} window.copyText=copyText;
function toggleSubmit(){$('submitBtn').disabled=!$('paidCheck').checked} window.toggleSubmit=toggleSubmit;
const banks=[['Хаан банк','khanbank://','KH','khan'],['Хас банк','xacbank://','X','xac'],['TDB online','tdbbank://','TDB','tdb'],['Голомт банк','golomtbank://','G','golomt'],['qPay','qpay://','Q','qpay'],['Төрийн банк','statebank://','ТБ','state'],['MOST','mostmoney://','M','most'],['Капитрон','capitronbank://','K','capitron'],['Богд банк','bogdbank://','Б','bogd'],['M банк','mbank://','M','mbank'],['Ард','ard://','Ard','ard'],['Toki','toki://','Toki','toki'],['МонПэй','monpay://','Mon','monpay']];
function openBankModal(){let grid=$('bankGrid');grid.innerHTML=banks.map(b=>`<button class="bankApp" onclick="openBank('${b[1]}')"><div class="bankLogo ${b[3]}">${b[2]}</div><span>${b[0]}</span></button>`).join('');$('bankModal').classList.add('show')} window.openBankModal=openBankModal;
function closeBankModal(){$('bankModal').classList.remove('show')} window.closeBankModal=closeBankModal;
function openBank(url){copyText('accNo');setTimeout(()=>location.href=url,150)} window.openBank=openBank;
async function submitOrder(){if(!$('paidCheck').checked){toast('Төлбөр шилжүүлснээ батална уу');return}try{await addDoc(collection(db,'orders'),{client,package:selected,status:'Шинэ захиалга',paidConfirmed:true,date:new Date().toLocaleString('mn-MN'),createdAt:serverTimestamp(),updatedAt:Date.now()});showScreen('thanks')}catch(e){alert('Firebase алдаа: '+e.message)}} window.submitOrder=submitOrder;
function openAdmin(){let p=prompt('Админ нууц үг');if(p==='9999')showScreen('admin');else if(p)alert('Нууц үг буруу')} window.openAdmin=openAdmin;
async function loadOrders(){const box=$('orders');box.innerHTML='<div class="order card">Уншиж байна...</div>';try{let snap=await getDocs(query(collection(db,'orders'),orderBy('updatedAt','desc')));if(snap.empty){box.innerHTML='<div class="order card">Захиалга алга</div>';return}box.innerHTML='';snap.forEach(d=>{let o=d.data(),link=location.origin+location.pathname+'#report='+d.id;box.innerHTML+=`<div class="order card"><h3>${o.client?.fullName||''} — ${o.package?.name||''}</h3><p>Утас: ${o.client?.phone||''}</p><p>Төрсөн: ${o.client?.birth||''}</p><p>Үнэ: ${Number(o.package?.price||0).toLocaleString('mn-MN')}₮</p><p>Төлөв: ${o.status||''}</p><div class="actions"><button class="gold" onclick="markDone('${d.id}')">Баталгаажсан</button><button class="outline" onclick="navigator.clipboard.writeText('${link}');alert('Линк хууллаа')">Линк хуулах</button><button class="outline" onclick="location.href='sms:${o.client?.phone||''}?body='+encodeURIComponent('Тэнгэрийн Мэлмий: Таны тайлан бэлэн боллоо. ${link}')">SMS</button></div></div>`})}catch(e){box.innerHTML='<div class="order card">Firestore алдаа: '+e.message+'</div>'}} window.loadOrders=loadOrders;
async function markDone(id){await updateDoc(doc(db,'orders',id),{status:'Баталгаажсан',updatedAt:Date.now()});loadOrders()} window.markDone=markDone;
function tick(){let now=new Date(),end=new Date();end.setHours(24,0,0,0);let s=Math.max(0,Math.floor((end-now)/1000));$('timer').textContent=[Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(x=>String(x).padStart(2,'0')).join(':')}setInterval(tick,1000);tick();
if('serviceWorker' in navigator){navigator.serviceWorker.register('sw.js').catch(()=>{})}
